<?php  //[STAMP] 55067d27b6c6b7eb9280358eb7ada890
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile



trait Actions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
